### ISSUE TITLE
Cuda out of memory for batch_size=1

### ISSUE THREAD

**Issue by rishikeshraj5** [Data-Science-kosta/Speech-Emotion-Classification-with-PyTorch#3]
Hi there, Just started reusing your first model, stacked _cnn , all work fine until training.
Even for batch_size=1
its throwing an error: cuda out of memory.

is there any other solution for this? I think you have not used any dataloaders here probably that's the reason , plz explain and guide what to do?

**Comment by rishikeshraj5** [comment]
I tried using kaggle too , there also I am getting similar error
**Your notebook tried to allocate more memory than is available. It has restarted.**

 Basically it stops before training every time similar to my local machine, can you resolve this plz sir?
Regards

**Comment by kosta-jo** [comment]
@rishikeshraj5 I assume you probably have low memory GPU, that is the reason why you get cuda out of memory error on your computer. On Kaggle there is around 13GB of RAM memory now, and back then it was around 16GB. So, the complete dataset can not fit into the RAM. You will have to rewrite the code to load only 1 batch at the time into the RAM.

**Comment by rishikeshraj5** [comment]
Sir could you plz direct me to some reference for that,as I don't know how to modify it please
Even its not working in colab :(
How to load one batch at a time.

**Comment by kosta-jo** [comment]
Process the data and save it on the hard disk and create [pytorch dataloader](https://pytorch.org/tutorials/beginner/data_loading_tutorial.html)

**Comment by rishikeshraj5** [comment]
So sir you are saying I need to save all variables from editor into hard disk?
Sir I have executed till I get

Shape of X_train:  (3441, 7, 1, 128, 128)
Shape of X_val:  (143, 7, 1, 128, 128)
Shape of X_test:  (150, 7, 1, 128, 128)

so this the data to be used by the model, which can be further used by pytorch dataloader.
Sir If my understanding is correct as of now,plz guide further.

**Comment by kosta-jo** [comment]
Now you save on hard disk each example, out of 3441 in train set, in separate files and you implement Data Loader to load for example 32 files at the time (if you want batch size to be 32). It is pretty basic you should watch some tutorials.
